application: leads-search
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/images/(.*\.(gif|png|jpg))
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: leads_form.py